@startuml
class GameDisplay {
    +print(Gb :GameBoard) : void
}

class GameManager {
    -status :int
    -board :GameBoard
    -display : GameDisplay

    +processInput(inp :string) : void
}

class GameBoard {
    -sizeX : int
    -sizeY : int

    -grid : Cell[sizeX][sizeY]

    +__init__()

    +reveal(x, y :int) : bool
    +toggleFlagged(x, y :int) : void

    -populate() : void
    -propagateFrom(x, y :int) : void

}

class Cell {

    -flagged : bool
    -bomb : bool
    -hidden : bool
    -nearby_bombs : int

    +is_bomb() : bool
    -set_bomb(bomb :bool) : void

    +is_flagged() : bool
    +set_flagged(flagged :bool) : void

    +is_hidden() : bool
    +set_hidden(hidden: bool) : void

    +get_nearby_bombs() : int
    +set_nearby_bombs(nearby_bombs: int) : void
}

@enduml